[3/2, 10:07 PM] +255 752 120 064: ã€Œ *`BADBOY-BOT`* ã€
 
*Hey!*John_Tech*
 
 
*â€¢ DATE:*  ```03/03/2025```
*â€¢ TIME:*  ```12:07 AM (ğŸ‡µğŸ‡°)``` 
*â€¢ UPTIME:*  ```20:04:26```
*â€¢ happy early in the dayâ˜€ï¸*


 â”Œâ”€â– John _Tech MD COMMANDS* â–â”€â”  
â”‚ 
â”œ âœ§ ğŸ“š *.Studymenu*  
â”œ âœ§ ğŸ‘‘ *.Ownermenu*  
â”œ âœ§ ğŸ’Œ *.Botmenu*  
â”œ âœ§ ğŸ§¬ *.Groupmenu*  
â”œ âœ§ ğŸ“¥ *.DLmenu*  
â”œ âœ§ ğŸ§° *.Toolsmenu*  
â”œ âœ§ ğŸ¨ *.Stickermenu*  
â”œ âœ§ ğŸ‰ *.Funmenu*  
â”œ âœ§ ğŸ® *.Gamemenu*  
â”œ âœ§ ğŸ© *.Logomenu*  
â”œ âœ§ ğŸ“ƒ *.list*
â”œ âœ§ ğŸ“œ *.Menu2*    
â”‚  
â””â”€â”€â”€â”€â”€â”€â”€â”€â”€ â˜… â˜… â˜… â”€â”€â”€â”€â”€â”€â”€â”€â”€â”˜
â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€â€


*`â—‰ ğŸ“š STUDY CMDS`*
â•‘
â•  â—‹ *.deepseek <texts>*
â•‘
â•  â—‹ *.dpsk <texts>*
â•‘
â•  â—‹ *.acloudai <query>*
â•‘
â•  â—‹ *.bmg*
â•‘
â•  â—‹ *.bardimg*
â•‘
â•  â—‹ *.bard*
â•‘
â•  â—‹ *.gemini <query>*
â•‘
â•  â—‹ *.define <word>*
â•‘
â•  â—‹ *.groq <query>*
â•‘
â•  â—‹ *.gr*
â•‘
â•  â—‹ *.google <search term>*
â•‘
â•  â—‹ *.googlef <search term>*
â•‘
â•  â—‹ *.population*
â•‘
â•  â—‹ *.aisearch <query>*
â•‘
â•  â—‹ *.bot <query>*
â•‘
â•  â—‹ *.prince <query>*
â•‘
â•  â—‹ *.aivoice*
â•šâ€¢ 


*`â—‰ ğŸ“¥ DOWNLOADERS CMDS`*
â•‘
â•  â—‹ *.facebook <link>*
â•‘
â•  â—‹ *.facebook3/fb3 <link fb>*
â•‘
â•  â—‹ *.gdrive*
â•‘
â•  â—‹ *.gitclone <url>*
â•‘
â•  â—‹ *.igstalk*
â•‘
â•  â—‹ *.instagram <link ig>*
â•‘
â•  â—‹ *.instagram2 <link ig>*
â•‘
â•  â—‹ *.mediafire <url>*
â•‘
â•  â—‹ *.mega*
â•‘
â•  â—‹ *.apk*
â•‘
â•  â—‹ *.apkmod*
â•‘
â•  â—‹ *.play <query>*
â•‘
â•  â—‹ *.playvoice*
â•‘
â•  â—‹ *.tiktok <link>*
â•‘
â•  â—‹ *.tiktok2 <link tiktok>*
â•‘
â•  â—‹ *.tiktoksearch <query>*
â•‘
â•  â—‹ *.tiktokstalk*
â•‘
â•  â—‹ *.twitter <url>*
â•‘
â•  â—‹ *.playlist*
â•‘
â•  â—‹ *.yts*
â•‘
â•  â—‹ *.ytmp4 <YouTube link>*
â•‘
â•  â—‹ *.gitprince/gitp*
â•šâ€¢ 


*`â—‰ â„¹ï¸ INFOBOT CMDS`*
â•‘
â•  â—‹ *.allmenu*
â•‘
â•  â—‹ *.alive*
â•‘
â•  â—‹ *.info*
â•‘
â•  â—‹ *.channel*
â•‘
â•  â—‹ *.owner*
â•‘
â•  â—‹ *.support*
â•‘
â•  â—‹ *.language <es-en..>*
â•‘
â•  â—‹ *.listprem*
â•‘
â•  â—‹ *.help*
â•‘
â•  â—‹ *.play*
â•‘
â•  â—‹ *.list*
â•‘
â•  â—‹ *.botmenu*
â•‘
â•  â—‹ *.ownermenu*
â•‘
â•  â—‹ *.groupmenu*
â•‘
â•  â—‹ *.dlmenu*
â•‘
â•  â—‹ *.downloadermenu*
â•‘
â•  â—‹ *.economymenu*
â•‘
â•  â—‹ *.funmenu*
â•‘
â•  â—‹ *.gamemenu*
â•‘
â•  â—‹ *.stickermenu*
â•‘
â•  â—‹ *.logomenu*
â•‘
â•  â—‹ *.toolmenu*
â•‘
â•  â—‹ *.ping*
â•‘
â•  â—‹ *.runtime*
â•‘
â•  â—‹ *.script*
â•‘
â•  â—‹ *.allmenu*
â•‘
â•  â—‹ *.nowa <number>*
â•šâ€¢ 


*`â—‰ ğŸ‘‘ OWNER CMDS`*
â•‘
â•  â—‹ *.broadcastgroup <text>*
â•‘
â•  â—‹ *.bcgc <text>*
â•‘
â•  â—‹ *.df*
â•‘
â•  â—‹ *.blocklist*
â•‘
â•  â—‹ *.allow <@tag>*
â•‘
â•  â—‹ *.allvars*
â•‘
â•  â—‹ *.addprem <@tag>*
â•‘
â•  â—‹ *.addowner @user*
â•‘
â•  â—‹ *.allowedlist*
â•‘
â•  â—‹ *.banchat*
â•‘
â•  â—‹ *.listban*
â•‘
â•  â—‹ *.tx*
â•‘
â•  â—‹ *.broadcastgroup <text>*
â•‘
â•  â—‹ *.bcgc <text>*
â•‘
â•  â—‹ *.cleartmp*
â•‘
â•  â—‹ *.delexpired*
â•‘
â•  â—‹ *.delprem @user*
â•‘
â•  â—‹ *.removeowner @user*
â•‘
â•  â—‹ *.getplugin <name file>*
â•‘
â•  â—‹ *.getfile <name file>*
â•‘
â•  â—‹ *.join <chat.whatsapp.com> <dias>*
â•‘
â•  â—‹ *.checkupdate*
â•‘
â•  â—‹ *.autoupdate*
â•‘
â•  â—‹ *.removeallow <@tag>*
â•‘
â•  â—‹ *.reset <92xxx>*
â•‘
â•  â—‹ *.resetprefix*
â•‘
â•  â—‹ *.restart*
â•‘
â•  â—‹ *..setprefix [symbol]*
â•‘
â•  â—‹ *.unbanuser*
â•‘
â•  â—‹ *.unbanchat*
â•‘
â•  â—‹ *.var Name/Value*
â•‘
â•  â—‹ *.setvar Name,Value*
â•‘
â•  â—‹ *.deleteplugin <name>*
â•‘
â•  â—‹ *.sf <text>*
â•šâ€¢ 


*`â—‰ âš™ï¸ GROUP CMDS`*
â•‘
â•  â—‹ *.add*
â•‘
â•  â—‹ *.approve*
â•‘
â•  â—‹ *.approveall*
â•‘
â•  â—‹ *.delete*
â•‘
â•  â—‹ *.delwarn @user*
â•‘
â•  â—‹ *.demote (@tag)*
â•‘
â•  â—‹ *.grouptime *<open/close>* *<number>**
â•‘
â•  â—‹ *.infogp*
â•‘
â•  â—‹ *.setgdp*
â•‘
â•  â—‹ *.hidetag*
â•‘
â•  â—‹ *.invite <9230xxx>*
â•‘
â•  â—‹ *.kick @user*
â•‘
â•  â—‹ *.kick2 @user*
â•‘
â•  â—‹ *.kk @user*
â•‘
â•  â—‹ *.kick3 @user*
â•‘
â•  â—‹ *.kkk @user*
â•‘
â•  â—‹ *.link*
â•‘
â•  â—‹ *.poll question|option|option*
â•‘
â•  â—‹ *.profile*
â•‘
â•  â—‹ *.promote*
â•‘
â•  â—‹ *.resetlink*
â•‘
â•  â—‹ *.setbye <text>*
â•‘
â•  â—‹ *.setrules <text>*
â•‘
â•  â—‹ *.mute*
â•‘
â•  â—‹ *.close*
â•‘
â•  â—‹ *.unmute*
â•‘
â•  â—‹ *.open*
â•‘
â•  â—‹ *.simulate <event> @user*
â•‘
â•  â—‹ *.staff*
â•‘
â•  â—‹ *.tagall*
â•‘
â•  â—‹ *.totag*
â•‘
â•  â—‹ *.warn @user*
â•‘
â•  â—‹ *.setwelcome <text>*
â•‘
â•  â—‹ *.kicknum*
â•‘
â•  â—‹ *.listnum*
â•‘
â•  â—‹ *.listjoin*
â•‘
â•  â—‹ *.checkexpired*
â•šâ€¢ 


*`â—‰ ğŸ’» JADIBOT CMDS`*
â•‘
â•  â—‹ *.jadibot*
â•‘
â•  â—‹ *.botlist*
â•‘
â•  â—‹ *.txbot*
â•‘
â•  â—‹ *.stop*
â•šâ€¢ 


*`â—‰ ğŸ”§ TOOLS CMDS`*
â•‘
â•  â—‹ *.getpair*
â•‘
â•  â—‹ *.pair*
â•‘
â•  â—‹ *.npmjs*
â•‘
â•  â—‹ *.shortpair*
â•‘
â•  â—‹ *.shortcode*
â•‘
â•  â—‹ *statussave*
â•‘
â•  â—‹ *.tempmail*
â•‘
â•  â—‹ *.get*
â•‘
â•  â—‹ *.readvo*
â•‘
â•  â—‹ *.length <amount>*
â•‘
â•  â—‹ *.tinyurl <link>*
â•‘
â•  â—‹ *.shorten <link>*
â•‘
â•  â—‹ *.gdsai*
â•‘
â•  â—‹ *.cal <equation>*
â•‘
â•  â—‹ *..carbon <code>*
â•‘
â•  â—‹ *.element*
â•‘
â•  â—‹ *.fake <text> @user <text2>*
â•‘
â•  â—‹ *.forward <targetJid1,targetJid2,...> [<text> | <media>]*
â•‘
â•  â—‹ *.gdsai*
â•‘
â•  â—‹ *.fetch2*
â•‘
â•  â—‹ *.get2*
â•‘
â•  â—‹ *.getjid*
â•‘
â•  â—‹ *.Enhance*
â•‘
â•  â—‹ *.hdfull*
â•‘
â•  â—‹ *.fullhd*
â•‘
â•  â—‹ *.itunes*
â•‘
â•  â—‹ *.lyrics*
â•‘
â•  â—‹ *.imdb*
â•‘
â•  â—‹ *.npm <package-name>*
â•‘
â•  â—‹ *.ocr*
â•‘
â•  â—‹ *.dehaze*
â•‘
â•  â—‹ *.recolor*
â•‘
â•  â—‹ *.hdr*
â•‘
â•  â—‹ *.readmore <text1>|<text2>*
â•‘
â•  â—‹ *.read2*
â•‘
â•  â—‹ *.removebg*
â•‘
â•  â—‹ *.ss <url>*
â•‘
â•  â—‹ *.ssf <url>*
â•‘
â•  â—‹ *.subreddit*
â•‘
â•  â—‹ *.fancy <text>*
â•‘
â•  â—‹ *.telesticker* (â““)
â•‘
â•  â—‹ *.tourl*
â•‘
â•  â—‹ *.translate <lang> <text>*
â•‘
â•  â—‹ *.true*
â•‘
â•  â—‹ *.tts <lang> <task>*
â•‘
â•  â—‹ *.wa*
â•‘
â•  â—‹ *.weather *<place>**
â•‘
â•  â—‹ *.wikipedia*
â•‘
â•  â—‹ *.shazam*
â•šâ€¢ 


*`â—‰ ğŸ® GAMES CMDS`*
â•‘
â•  â—‹ *.chess [from to]*
â•‘
â•  â—‹ *.chess delete*
â•‘
â•  â—‹ *.chess join*
â•‘
â•  â—‹ *.chess start*
â•‘
â•  â—‹ *.dado*
â•‘
â•  â—‹ *.delttt*
â•‘
â•  â—‹ *.guessflag*
â•‘
â•  â—‹ *.Maths <modes>*
â•‘
â•  â—‹ *.ppt <rock/paper/scissors>*
â•‘
â•  â—‹ *.slot <apuesta>*
â•‘
â•  â—‹ *.tictactoe <tag number>*
â•šâ€¢ 


*`â—‰ ğŸŸ¢ REGISTRY CMDS`*
â•‘
â•  â—‹ *.reg <name.age>*
â•‘
â•  â—‹ *.register <name.age>*
â•‘
â•  â—‹ *.mysn*
â•‘
â•  â—‹ *.unreg <Num Serie>*
â•šâ€¢ 


*`â—‰ ğŸ•¹ BOT SETTINGS`*
â•‘
â•  â—‹ *.enable <option>*
â•‘
â•  â—‹ *.disable <option>*
â•šâ€¢ 


*`â—‰ ğŸ” SEARCH CMDS`*
â•‘
â•  â—‹ *.pinterest <video url>*
â•šâ€¢ 


*`â—‰ ğŸ§§ STICKER CMDS`*
â•‘
â•  â—‹ *.atp <text>*
â•‘
â•  â—‹ *.attp <text>*
â•‘
â•  â—‹ *.emojimix <emoji+emoji>*
â•‘
â•  â—‹ *.getsticker*
â•‘
â•  â—‹ *.smaker*
â•‘
â•  â—‹ *.sfull*
â•‘
â•  â—‹ *.toimg (reply)*
â•‘
â•  â—‹ *.tovid*
â•‘
â•  â—‹ *.trigger <@user>*
â•‘
â•  â—‹ *.ttp <text>*
â•‘
â•  â—‹ *.take <name>|<author>*
â•šâ€¢ 


*`â—‰ ğŸ›  RPG CMDS`*
â•šâ€¢ 


*`â—‰ ğŸˆ REACTIONS CMDS`*
â•‘
â•  â—‹ *.bully @tag*
â•‘
â•  â—‹ *.cuddle @tag*
â•‘
â•  â—‹ *.cry @tag*
â•‘
â•  â—‹ *.hug @tag*
â•‘
â•  â—‹ *.awoo @tag*
â•‘
â•  â—‹ *.kiss @tag*
â•‘
â•  â—‹ *.lick @tag*
â•‘
â•  â—‹ *.pat @tag*
â•‘
â•  â—‹ *.smug @tag*
â•‘
â•  â—‹ *.bonk @tag*
â•‘
â•  â—‹ *.yeet @tag*
â•‘
â•  â—‹ *.blush @tag*
â•‘
â•  â—‹ *.smile @tag*
â•‘
â•  â—‹ *.wave @tag*
â•‘
â•  â—‹ *.highfive @tag*
â•‘
â•  â—‹ *.handhold @tag*
â•‘
â•  â—‹ *.nom @tag*
â•‘
â•  â—‹ *.bite @tag*
â•‘
â•  â—‹ *.glomp @tag*
â•‘
â•  â—‹ *.slap @tag*
â•‘
â•  â—‹ *.kill @tag*
â•‘
â•  â—‹ *.happy @tag*
â•‘
â•  â—‹ *.wink @tag*
â•‘
â•  â—‹ *.poke @tag*
â•‘
â•  â—‹ *.dance @tag*
â•‘
â•  â—‹ *.cringe @tag*
â•šâ€¢ 


*`â—‰ ğŸ€ LOGOS CMDS`*
â•‘
â•  â—‹ *.blur*
â•‘
â•  â—‹ *.difuminar2*
â•‘
â•  â—‹ *.gfx1*
â•‘
â•  â—‹ *.gfx2*
â•‘
â•  â—‹ *.gfx3*
â•‘
â•  â—‹ *.gfx4*
â•‘
â•  â—‹ *.gfx5*
â•‘
â•  â—‹ *.gfx6*
â•‘
â•  â—‹ *.gfx7*
â•‘
â•  â—‹ *.gfx8*
â•‘
â•  â—‹ *.gfx9*
â•‘
â•  â—‹ *.gfx10*
â•‘
â•  â—‹ *.gfx11*
â•‘
â•  â—‹ *.gfx12*
â•‘
â•  â—‹ *.simpcard*
â•‘
â•  â—‹ *.itssostupid*
â•‘
â•  â—‹ *.iss*
â•‘
â•  â—‹ *.stupid*
â•‘
â•  â—‹ *.tweet <comment>*
â•‘
â•  â—‹ *.lolicon*
â•‘
â•  â—‹ *.ytcomment <comment>*
â•šâ€¢ 


*`â—‰ ğŸª„FUN CMDS`*
â•‘
â•  â—‹ *.afk <reason>*
â•‘
â•  â—‹ *.character @tag*
â•‘
â•  â—‹ *.dare*
â•‘
â•  â—‹ *.flirt*
â•‘
â•  â—‹ *.gay @user*
â•‘
â•  â—‹ *.pickupline*
â•‘
â•  â—‹ *.pregunta*
â•‘
â•  â—‹ *.question*
â•‘
â•  â—‹ *.shayari*
â•‘
â•  â—‹ *.ship*
â•‘
â•  â—‹ *.tomp3*
â•‘
â•  â—‹ *.toav*
â•‘
â•  â—‹ *.truth*
â•‘
â•  â—‹ *.txt*
â•‘
â•  â—‹ *.waste @user*
â•‘
â•  â—‹ *.quote*
â•šâ€¢ 


*`â—‰ ğŸ¶ AUDIO CMDS`*
â•‘
â•  â—‹ *.bass [vn]*
â•‘
â•  â—‹ *.blown [vn]*
â•‘
â•  â—‹ *.deep [vn]*
â•‘
â•  â—‹ *.earrape [vn]*
â•‘
â•  â—‹ *.fast [vn]*
â•‘
â•  â—‹ *.fat [vn]*
â•‘
â•  â—‹ *.nightcore [vn]*
â•‘
â•  â—‹ *.reverse [vn]*
â•‘
â•  â—‹ *.robot [vn]*
â•‘
â•  â—‹ *.slow [vn]*
â•‘
â•  â—‹ *.smooth [vn]*
â•‘
â•  â—‹ *.tupai [vn]*
â•šâ€¢ 


*`â—‰ img`*
â•‘
â•  â—‹ *.ppcouple*
â•‘
â•  â—‹ *.ppcp*
â•‘
â•  â—‹ *.imagen*
â•‘
â•  â—‹ *.wallpaper*
â•šâ€¢ 


*`â—‰ cmd`*
â•‘
â•  â—‹ *.delcmd <text>*
â•‘
â•  â—‹ *.listcmd*
â•‘
â•  â—‹ *.setcmd <txt>*
â•šâ€¢ 


*`â—‰ internet`*
â•‘
â•  â—‹ *.gimage <query> | <number>*
â•‘
â•  â—‹ *.imagen <query> | <number>*
â•‘
â•  â—‹ *.animequote*
â•šâ€¢ 


*`â—‰ Downloader`*
â•‘
â•  â—‹ *.gimage <query> | <number>*
â•‘
â•  â—‹ *.imagen <query> | <number>*
â•šâ€¢ 


*`â—‰ AI`*
â•‘
â•  â—‹ *.tocartoon*
â•‘
â•  â—‹ *.bingimg <query>*
â•‘
â•  â—‹ *.imagine*
â•šâ€¢ 


*`â—‰ advanced`*
â•‘
â•  â—‹ *: *
â•‘
â•  â—‹ *=: *
â•‘
â•  â—‹ *$*
â•šâ€¢ 


*`â—‰ plugin`*
â•‘
â•  â—‹ *.install <Gist URL>*
â•šâ€¢ 


*á´˜Ê€ÉªÉ´á´„á´‡ á´á´…*
[3/2, 10:08 PM] +255 752 120 064: *[ BOT â€¢ NAME:ğŸ“¦ ]*
> SILENT-SOBX-MD

*[ OWNER â€¢ NAME:ğŸª© ]*
> SILENTLOVER0432

*[ STARS:ğŸŒŸ ]*
> 6

*[ FORKS:ğŸš€ ]*
> 62

*[ GITHUB â€¢ LINK:ğŸ’« ]*
> https://github.com/SILENTLOVER0432/SILENT-SOBX-MD

*[ DESCRIPTION:ğŸ¤– ]*
> âœ§ã€–THE WORLD BEST WHATSAPP BOT CREATED BY SILENTLOVER432 â™¥ï¸ã€—âœ§

*DON'T FORGET TO STAR ğŸŒŸ AND FORK REPOSITORY ğŸš€*

> *Â© POWERED BY SILENTLOVER432 â™¥ï¸*
